_wandb:
    value:
        cli_version: 0.24.2
        e:
            c4ou2e77mb25egl685r9hrdhwoylwxfs:
                args:
                    - --wandb.enable=True
                    - --wandb.project=tlof-VLA-v4
                    - --wandb.entity=x-k
                    - --policy.path=HuggingFaceVLA/smolvla_libero
                    - --dataset.repo_id=HuggingFaceVLA/libero
                    - --dataset.streaming=True
                    - --optimizer.type=adamw
                    - --optimizer.lr=1e-5
                    - --optimizer.weight_decay=1e-4
                    - --optimizer.grad_clip_norm=1.0
                    - --env.type=libero
                    - --env.task=libero_object
                    - --steps=1000
                    - --eval_freq=1000
                    - --log_freq=1
                    - --save_freq=100
                    - --output_dir=./train_logs/libero_object_tlofVLA_v4
                    - --resume=True
                    - --policy.device=cuda
                    - --eval.batch_size
                    - "4"
                    - --eval.use_async_envs=False
                codePath: lerobot/scripts/tlofVLA_train（v3）.py
                codePathLocal: lerobot/scripts/tlofVLA_train（v3）.py
                cpu_count: 104
                cpu_count_logical: 208
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "32212254720"
                        used: "14336139264"
                executable: /root/autodl-tmp/miniconda3/envs/lerobot/bin/python
                git:
                    commit: 452d3dc05a4e80e36d6d61e3fca6666cba5cb2e4
                    remote: git@github.com:xkkkkkkkkkkk/DORF-VLA.git
                gpu: NVIDIA GeForce RTX 4090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 16384
                      memoryTotal: "51527024640"
                      name: NVIDIA GeForce RTX 4090
                      uuid: GPU-01119529-b8f4-1b79-71bb-92b934ead110
                host: autodl-container-wtcnbd3acn-93a2ef74
                memory:
                    total: "810158297088"
                os: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
                program: /root/autodl-tmp/lerobot/src/lerobot/scripts/tlofVLA_train（v3）.py
                python: CPython 3.10.19
                root: train_logs/libero_object_tlofVLA_v4
                startedAt: "2026-05-05T14:17:03.586241Z"
                writerId: c4ou2e77mb25egl685r9hrdhwoylwxfs
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 83
            "3":
                - 13
                - 15
                - 16
            "4": 3.10.19
            "5": 0.24.2
            "6": 5.1.0
            "10":
                - 21
            "12": 0.24.2
            "13": linux-x86_64
batch_size:
    value: 4
checkpoint_path:
    value: null
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                affine:
                    kwargs:
                        degrees:
                            - -5
                            - 5
                        translate:
                            - 0.05
                            - 0.05
                    type: RandomAffine
                    weight: 1
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: HuggingFaceVLA/libero
        revision: null
        root: null
        streaming: true
        use_imagenet_stats: true
        video_backend: torchcodec
env:
    value:
        camera_name: agentview_image,robot0_eye_in_hand_image
        camera_name_mapping: null
        control_mode: relative
        disable_env_checker: true
        episode_length: null
        features:
            action:
                shape:
                    - 7
                type: ACTION
            pixels/agentview_image:
                shape:
                    - 360
                    - 360
                    - 3
                type: VISUAL
            pixels/robot0_eye_in_hand_image:
                shape:
                    - 360
                    - 360
                    - 3
                type: VISUAL
            robot_state/eef/mat:
                shape:
                    - 3
                    - 3
                type: STATE
            robot_state/eef/pos:
                shape:
                    - 3
                type: STATE
            robot_state/eef/quat:
                shape:
                    - 4
                type: STATE
            robot_state/gripper/qpos:
                shape:
                    - 2
                type: STATE
            robot_state/gripper/qvel:
                shape:
                    - 2
                type: STATE
            robot_state/joints/pos:
                shape:
                    - 7
                type: STATE
            robot_state/joints/vel:
                shape:
                    - 7
                type: STATE
        features_map:
            action: action
            pixels/agentview_image: observation.images.image
            pixels/robot0_eye_in_hand_image: observation.images.image2
            robot_state/eef/mat: observation.state.eef_mat
            robot_state/eef/pos: observation.state.eef_pos
            robot_state/eef/quat: observation.state.eef_quat
            robot_state/gripper/qpos: observation.state.gripper_qpos
            robot_state/gripper/qvel: observation.state.gripper_qvel
            robot_state/joints/pos: observation.state.joint_pos
            robot_state/joints/vel: observation.state.joint_vel
        fps: 30
        init_states: true
        max_parallel_tasks: 1
        obs_type: pixels_agent_pos
        observation_height: 360
        observation_width: 360
        render_mode: rgb_array
        task: libero_object
        task_ids: null
        type: libero
eval:
    value:
        batch_size: 4
        n_episodes: 50
        use_async_envs: false
eval_freq:
    value: 1000
job_name:
    value: libero_smolvla
log_freq:
    value: 1
num_workers:
    value: 2
optimizer:
    value:
        betas:
            - 0.9
            - 0.999
        eps: 1e-08
        grad_clip_norm: 1
        lr: 1e-05
        type: adamw
        weight_decay: 0.0001
output_dir:
    value: train_logs/libero_object_tlofVLA_v4
peft:
    value: null
policy:
    value:
        adapt_to_pi_aloha: false
        add_image_special_tokens: false
        attention_mode: cross_attn
        chunk_size: 50
        device: cuda
        empty_cameras: 0
        expert_width_multiplier: 0.5
        freeze_vision_encoder: true
        input_features:
            observation.images.image:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.images.image2:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.state:
                shape:
                    - 8
                type: STATE
        license: null
        load_vlm_weights: true
        max_action_dim: 32
        max_period: 4
        max_state_dim: 32
        min_period: 0.004
        n_action_steps: 1
        n_obs_steps: 1
        normalization_mapping:
            ACTION: MEAN_STD
            STATE: MEAN_STD
            VISUAL: IDENTITY
        num_expert_layers: -1
        num_steps: 10
        num_vlm_layers: 0
        optimizer_betas:
            - 0.9
            - 0.95
        optimizer_eps: 1e-08
        optimizer_grad_clip_norm: 10
        optimizer_lr: 0.0001
        optimizer_weight_decay: 1e-10
        output_features:
            action:
                shape:
                    - 7
                type: ACTION
        pad_language_to: longest
        prefix_length: 0
        pretrained_path: HuggingFaceVLA/smolvla_libero
        private: null
        push_to_hub: true
        repo_id: None
        resize_imgs_with_padding:
            - 512
            - 512
        rtc_config: null
        scheduler_decay_lr: 2.5e-06
        scheduler_decay_steps: 30000
        scheduler_warmup_steps: 1000
        self_attn_every_n_layers: 2
        tags: null
        tokenizer_max_length: 48
        train_expert_only: true
        train_state_proj: true
        type: smolvla
        use_amp: false
        use_cache: true
        use_delta_joint_actions_aloha: false
        use_peft: false
        vlm_model_name: HuggingFaceTB/SmolVLM2-500M-Instruct
rabc_epsilon:
    value: 1e-06
rabc_head_mode:
    value: sparse
rabc_kappa:
    value: 0.01
rabc_progress_path:
    value: null
resume:
    value: true
save_checkpoint:
    value: true
save_freq:
    value: 100
scheduler:
    value: null
seed:
    value: 1000
steps:
    value: 1000
tolerance_s:
    value: 0.0001
use_policy_training_preset:
    value: true
use_rabc:
    value: false
wandb:
    value:
        disable_artifact: false
        enable: true
        entity: x-k
        mode: null
        notes: null
        project: tlof-VLA-v4
        run_id: null
